apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mx64d7t17-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mx64d7t17-go 
  name: mx64d7t17-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mx64d7t17-go 
